-- Add remaining User entity columns (align TypeORM entity with schema)

ALTER TABLE users ADD COLUMN IF NOT EXISTS nationality VARCHAR(10) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_type VARCHAR(20) NOT NULL DEFAULT 'CONSUMER';
ALTER TABLE users ADD COLUMN IF NOT EXISTS linked_user_id UUID NULL REFERENCES users(id);
ALTER TABLE users ADD COLUMN IF NOT EXISTS kyc_status VARCHAR(20) NOT NULL DEFAULT 'PENDING';
ALTER TABLE users ADD COLUMN IF NOT EXISTS risk_score INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP NULL;
